dist: xenial
language: node_js
node_js:
  - "10"

services:
  - postgresql

install: "yarn install"

before_script:
  - psql -c 'create database electron_crash_report_server_test;' -U postgres

script:
  - yarn lint
  - yarn test || true && yarn test
