version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: yarn dev
    environment:
      - DATABASE_URL=postgres://example:example@db/electron-crash-report-server
      - AUTH_USER=crash
      - AUTH_PASS=electron
      - PORT=7777
    ports:
      - 80:7777
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=electron-crash-report-server
