version: 2

jobs:
  build:
    working_directory: ~/electron-crash-report-server

    docker:
      - image: circleci/node:10
        environment:
          DATABASE_URL: postgres://root@localhost/electron_crash_report_server_test
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: electron_crash_report_server_test

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: sudo apt install -y postgresql-client || true
      - run: yarn lint
      - run: yarn test || true && yarn test
