version: 2

jobs:
  build:
    working_directory: ~/electron-crash-report-server
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: |
            which yarn
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: yarn test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
